### ISSUE TITLE
a few missing dependencies in `requirements.txt`

### ISSUE THREAD

**Issue by gtsambos** [quinlan-lab/proj-mutator-mapping#3]
- `bx`
 - `pyfaidx`

... if I run into any others, I'll let you know here! Thanks again :)

**Comment by tomsasani** [comment]
These two should be included in the `requirements.txt` file at the moment (`bx-python==0.9.0` and `pyfaidx==0.7.2.1`) -- I'm able to run the full pipeline with a fresh install of the requirements on my end. Could you share a more detailed error message?

**Comment by gtsambos** [comment]
Hmm, strange. Maybe I wasn't paying close enough attention to the terminal messages when I was installing the `requirements.txt` file. I've since noticed this behaviour with a few other packages in this file (eg. `numba`), so I'll assume it's a problem on my end and close the issue.

**Comment by gtsambos** [comment]
`statsmodels` might genuinely be missing

**Comment by tomsasani** [comment]
Ahh, I believe `statsmodels` should be installed as a dependency of `statannotations` -- but probably a good idea to include that as its own requirement. To be safe, I think I might just update the `requirements.txt` to be a `pip freeze` of the complete env needed to reproduce figs/analysis.
